// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi9x5FS9je8GyMQMVnR1XE6wv4v1YTrDU',
    appId: '1:262465598021:web:cf5519eb04d19aa4c8a92c',
    messagingSenderId: '262465598021',
    projectId: 'gen-ai-hackathon-3a0d4',
    authDomain: 'gen-ai-hackathon-3a0d4.firebaseapp.com',
    storageBucket: 'gen-ai-hackathon-3a0d4.firebasestorage.app',
    measurementId: 'G-3637ZXDP4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVtWjpJzKNiIPuuVKGmhH5HXsnOht-o9A',
    appId: '1:262465598021:android:d35949bf23a3bbfec8a92c',
    messagingSenderId: '262465598021',
    projectId: 'gen-ai-hackathon-3a0d4',
    storageBucket: 'gen-ai-hackathon-3a0d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw4eJn3-ojciePgz8zPEynrNzid5Gqdlw',
    appId: '1:262465598021:ios:0ae98314d14ed44fc8a92c',
    messagingSenderId: '262465598021',
    projectId: 'gen-ai-hackathon-3a0d4',
    storageBucket: 'gen-ai-hackathon-3a0d4.firebasestorage.app',
    iosBundleId: 'com.example.genAiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw4eJn3-ojciePgz8zPEynrNzid5Gqdlw',
    appId: '1:262465598021:ios:0ae98314d14ed44fc8a92c',
    messagingSenderId: '262465598021',
    projectId: 'gen-ai-hackathon-3a0d4',
    storageBucket: 'gen-ai-hackathon-3a0d4.firebasestorage.app',
    iosBundleId: 'com.example.genAiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi9x5FS9je8GyMQMVnR1XE6wv4v1YTrDU',
    appId: '1:262465598021:web:f92169a48e9ea230c8a92c',
    messagingSenderId: '262465598021',
    projectId: 'gen-ai-hackathon-3a0d4',
    authDomain: 'gen-ai-hackathon-3a0d4.firebaseapp.com',
    storageBucket: 'gen-ai-hackathon-3a0d4.firebasestorage.app',
    measurementId: 'G-53F1HT54W3',
  );

}